/**
 * auto generated by graphql-codegen
 * DO NOT EDIT THIS FILE BY HAND
 */

type Maybe<T> = T | null
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
  DateTime: any
}

/** An event venue */
export type EventVenue = {
  city: Scalars['String']
  country: Scalars['String']
  lat: Scalars['Float']
  lon: Scalars['Float']
  name: Scalars['String']
  street: Scalars['String']
}

/** A meetup organizer */
export type Organizer = {
  description: Scalars['String']
  name: Scalars['String']
  profileImageUrl: Scalars['String']
  twitterName: Scalars['String']
}

/** The query root of Paderborn.js GraphQL interface */
export type Query = {
  /** Return a list of meetup organizers */
  organizers: Array<Organizer>
  /** Return a list of upcoming events */
  upcomingEvents: Array<UpcomingEvent>
}

/** A speaker */
export type Speaker = {
  avatarUrl: Scalars['String']
  name: Scalars['String']
  occupation: Scalars['String']
  socialName?: Maybe<Scalars['String']>
  socialUrl?: Maybe<Scalars['String']>
}

/** A talk */
export type Talk = {
  date: Scalars['DateTime']
  description: Scalars['String']
  isLightningTalk: Scalars['Boolean']
  labels: Array<Scalars['String']>
  speaker: Speaker
  title: Scalars['String']
}

/** An upcoming meetup event */
export type UpcomingEvent = {
  date: Scalars['DateTime']
  goingCount: Scalars['Int']
  url: Scalars['String']
  venue: EventVenue
  talks: Array<Talk>
}
import { ContextType } from '../utils/createContext'

import {
  GraphQLResolveInfo,
  GraphQLScalarType,
  GraphQLScalarTypeConfig,
} from 'graphql'

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult

export type StitchingResolver<TResult, TParent, TContext, TArgs> = {
  fragment: string
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>
}

export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => AsyncIterator<TResult> | Promise<AsyncIterator<TResult>>

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs>
  resolve?: SubscriptionResolveFn<TResult, TParent, TContext, TArgs>
}

export type SubscriptionResolver<
  TResult,
  TParent = {},
  TContext = {},
  TArgs = {}
> =
  | ((
      ...args: any[]
    ) => SubscriptionResolverObject<TResult, TParent, TContext, TArgs>)
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<TTypes>

export type NextResolverFn<T> = () => Promise<T>

export type DirectiveResolverFn<
  TResult = {},
  TParent = {},
  TContext = {},
  TArgs = {}
> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
  Query: Query
  Organizer: Organizer
  String: Scalars['String']
  UpcomingEvent: UpcomingEvent
  DateTime: Scalars['DateTime']
  Int: Scalars['Int']
  EventVenue: EventVenue
  Float: Scalars['Float']
  Talk: Talk
  Boolean: Scalars['Boolean']
  Speaker: Speaker
}

export interface DateTimeScalarConfig
  extends GraphQLScalarTypeConfig<ResolversTypes['DateTime'], any> {
  name: 'DateTime'
}

export type EventVenueResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['EventVenue']
> = {
  city?: Resolver<ResolversTypes['String'], ParentType, Context>
  country?: Resolver<ResolversTypes['String'], ParentType, Context>
  lat?: Resolver<ResolversTypes['Float'], ParentType, Context>
  lon?: Resolver<ResolversTypes['Float'], ParentType, Context>
  name?: Resolver<ResolversTypes['String'], ParentType, Context>
  street?: Resolver<ResolversTypes['String'], ParentType, Context>
}

export type OrganizerResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['Organizer']
> = {
  description?: Resolver<ResolversTypes['String'], ParentType, Context>
  name?: Resolver<ResolversTypes['String'], ParentType, Context>
  profileImageUrl?: Resolver<ResolversTypes['String'], ParentType, Context>
  twitterName?: Resolver<ResolversTypes['String'], ParentType, Context>
}

export type QueryResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['Query']
> = {
  organizers?: Resolver<Array<ResolversTypes['Organizer']>, ParentType, Context>
  upcomingEvents?: Resolver<
    Array<ResolversTypes['UpcomingEvent']>,
    ParentType,
    Context
  >
}

export type SpeakerResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['Speaker']
> = {
  avatarUrl?: Resolver<ResolversTypes['String'], ParentType, Context>
  name?: Resolver<ResolversTypes['String'], ParentType, Context>
  occupation?: Resolver<ResolversTypes['String'], ParentType, Context>
  socialName?: Resolver<Maybe<ResolversTypes['String']>, ParentType, Context>
  socialUrl?: Resolver<Maybe<ResolversTypes['String']>, ParentType, Context>
}

export type TalkResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['Talk']
> = {
  date?: Resolver<ResolversTypes['DateTime'], ParentType, Context>
  description?: Resolver<ResolversTypes['String'], ParentType, Context>
  isLightningTalk?: Resolver<ResolversTypes['Boolean'], ParentType, Context>
  labels?: Resolver<Array<ResolversTypes['String']>, ParentType, Context>
  speaker?: Resolver<ResolversTypes['Speaker'], ParentType, Context>
  title?: Resolver<ResolversTypes['String'], ParentType, Context>
}

export type UpcomingEventResolvers<
  Context = ContextType,
  ParentType = ResolversTypes['UpcomingEvent']
> = {
  date?: Resolver<ResolversTypes['DateTime'], ParentType, Context>
  goingCount?: Resolver<ResolversTypes['Int'], ParentType, Context>
  url?: Resolver<ResolversTypes['String'], ParentType, Context>
  venue?: Resolver<ResolversTypes['EventVenue'], ParentType, Context>
  talks?: Resolver<Array<ResolversTypes['Talk']>, ParentType, Context>
}

export type Resolvers<Context = ContextType> = {
  DateTime?: GraphQLScalarType
  EventVenue?: EventVenueResolvers<Context>
  Organizer?: OrganizerResolvers<Context>
  Query?: QueryResolvers<Context>
  Speaker?: SpeakerResolvers<Context>
  Talk?: TalkResolvers<Context>
  UpcomingEvent?: UpcomingEventResolvers<Context>
}

/**
 * @deprecated
 * Use "Resolvers" root object instead. If you wish to get "IResolvers", add "typesPrefix: I" to your config.
 */
export type IResolvers<Context = ContextType> = Resolvers<Context>
