/**
 * auto generated by graphql-codegen
 * DO NOT EDIT THIS FILE BY HAND
 */

export type Maybe<T> = T | null

export type DateTime = any

// ====================================================
// Scalars
// ====================================================

// ====================================================
// Types
// ====================================================

export interface Query {
  organizers: Organizer[]

  upcomingEvents: Event[]
}

export interface Organizer {
  description: string

  name: string

  twitter: TwitterAccount
}

export interface TwitterAccount {
  name: string

  profileImageUrl: string
}

export interface Event {
  date: DateTime

  goingCount: number

  url: string

  venue: EventVenue

  talks: Talk[]
}

export interface EventVenue {
  city: string

  country: string

  lat: number

  lon: number

  name: string

  street: string
}

export interface Talk {
  date: DateTime

  description: string

  isLightningTalk: boolean

  labels: string[]

  speaker: Speaker

  title: string
}

export interface Speaker {
  avatarUrl: string

  name: string

  occupation: string

  socialName?: Maybe<string>

  socialUrl?: Maybe<string>
}

// ====================================================
// Arguments
// ====================================================

import {
  GraphQLResolveInfo,
  GraphQLScalarType,
  GraphQLScalarTypeConfig,
} from 'graphql'

import { ContextType } from '../utils/createContext'

export type Resolver<Result, Parent = {}, TContext = {}, Args = {}> = (
  parent: Parent,
  args: Args,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<Result> | Result

export interface ISubscriptionResolverObject<Result, Parent, TContext, Args> {
  subscribe<R = Result, P = Parent>(
    parent: P,
    args: Args,
    context: TContext,
    info: GraphQLResolveInfo
  ): AsyncIterator<R | Result> | Promise<AsyncIterator<R | Result>>
  resolve?<R = Result, P = Parent>(
    parent: P,
    args: Args,
    context: TContext,
    info: GraphQLResolveInfo
  ): R | Result | Promise<R | Result>
}

export type SubscriptionResolver<
  Result,
  Parent = {},
  TContext = {},
  Args = {}
> =
  | ((
      ...args: any[]
    ) => ISubscriptionResolverObject<Result, Parent, TContext, Args>)
  | ISubscriptionResolverObject<Result, Parent, TContext, Args>

export type TypeResolveFn<Types, Parent = {}, TContext = {}> = (
  parent: Parent,
  context: TContext,
  info: GraphQLResolveInfo
) => Maybe<Types>

export type NextResolverFn<T> = () => Promise<T>

export type DirectiveResolverFn<TResult, TArgs = {}, TContext = {}> = (
  next: NextResolverFn<TResult>,
  source: any,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => TResult | Promise<TResult>

export namespace QueryResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = {}> {
    organizers?: OrganizersResolver<Organizer[], TypeParent, TContext>

    upcomingEvents?: UpcomingEventsResolver<Event[], TypeParent, TContext>
  }

  export type OrganizersResolver<
    R = Organizer[],
    Parent = {},
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type UpcomingEventsResolver<
    R = Event[],
    Parent = {},
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace OrganizerResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = Organizer> {
    description?: DescriptionResolver<string, TypeParent, TContext>

    name?: NameResolver<string, TypeParent, TContext>

    twitter?: TwitterResolver<TwitterAccount, TypeParent, TContext>
  }

  export type DescriptionResolver<
    R = string,
    Parent = Organizer,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type NameResolver<
    R = string,
    Parent = Organizer,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type TwitterResolver<
    R = TwitterAccount,
    Parent = Organizer,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace TwitterAccountResolvers {
  export interface Resolvers<
    TContext = ContextType,
    TypeParent = TwitterAccount
  > {
    name?: NameResolver<string, TypeParent, TContext>

    profileImageUrl?: ProfileImageUrlResolver<string, TypeParent, TContext>
  }

  export type NameResolver<
    R = string,
    Parent = TwitterAccount,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type ProfileImageUrlResolver<
    R = string,
    Parent = TwitterAccount,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace EventResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = Event> {
    date?: DateResolver<DateTime, TypeParent, TContext>

    goingCount?: GoingCountResolver<number, TypeParent, TContext>

    url?: UrlResolver<string, TypeParent, TContext>

    venue?: VenueResolver<EventVenue, TypeParent, TContext>

    talks?: TalksResolver<Talk[], TypeParent, TContext>
  }

  export type DateResolver<
    R = DateTime,
    Parent = Event,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type GoingCountResolver<
    R = number,
    Parent = Event,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type UrlResolver<
    R = string,
    Parent = Event,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type VenueResolver<
    R = EventVenue,
    Parent = Event,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type TalksResolver<
    R = Talk[],
    Parent = Event,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace EventVenueResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = EventVenue> {
    city?: CityResolver<string, TypeParent, TContext>

    country?: CountryResolver<string, TypeParent, TContext>

    lat?: LatResolver<number, TypeParent, TContext>

    lon?: LonResolver<number, TypeParent, TContext>

    name?: NameResolver<string, TypeParent, TContext>

    street?: StreetResolver<string, TypeParent, TContext>
  }

  export type CityResolver<
    R = string,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type CountryResolver<
    R = string,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type LatResolver<
    R = number,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type LonResolver<
    R = number,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type NameResolver<
    R = string,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type StreetResolver<
    R = string,
    Parent = EventVenue,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace TalkResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = Talk> {
    date?: DateResolver<DateTime, TypeParent, TContext>

    description?: DescriptionResolver<string, TypeParent, TContext>

    isLightningTalk?: IsLightningTalkResolver<boolean, TypeParent, TContext>

    labels?: LabelsResolver<string[], TypeParent, TContext>

    speaker?: SpeakerResolver<Speaker, TypeParent, TContext>

    title?: TitleResolver<string, TypeParent, TContext>
  }

  export type DateResolver<
    R = DateTime,
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type DescriptionResolver<
    R = string,
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type IsLightningTalkResolver<
    R = boolean,
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type LabelsResolver<
    R = string[],
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type SpeakerResolver<
    R = Speaker,
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type TitleResolver<
    R = string,
    Parent = Talk,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

export namespace SpeakerResolvers {
  export interface Resolvers<TContext = ContextType, TypeParent = Speaker> {
    avatarUrl?: AvatarUrlResolver<string, TypeParent, TContext>

    name?: NameResolver<string, TypeParent, TContext>

    occupation?: OccupationResolver<string, TypeParent, TContext>

    socialName?: SocialNameResolver<Maybe<string>, TypeParent, TContext>

    socialUrl?: SocialUrlResolver<Maybe<string>, TypeParent, TContext>
  }

  export type AvatarUrlResolver<
    R = string,
    Parent = Speaker,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type NameResolver<
    R = string,
    Parent = Speaker,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type OccupationResolver<
    R = string,
    Parent = Speaker,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type SocialNameResolver<
    R = Maybe<string>,
    Parent = Speaker,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
  export type SocialUrlResolver<
    R = Maybe<string>,
    Parent = Speaker,
    TContext = ContextType
  > = Resolver<R, Parent, TContext>
}

/** Directs the executor to skip this field or fragment when the `if` argument is true. */
export type SkipDirectiveResolver<Result> = DirectiveResolverFn<
  Result,
  SkipDirectiveArgs,
  ContextType
>
export interface SkipDirectiveArgs {
  /** Skipped when true. */
  if: boolean
}

/** Directs the executor to include this field or fragment only when the `if` argument is true. */
export type IncludeDirectiveResolver<Result> = DirectiveResolverFn<
  Result,
  IncludeDirectiveArgs,
  ContextType
>
export interface IncludeDirectiveArgs {
  /** Included when true. */
  if: boolean
}

/** Marks an element of a GraphQL schema as no longer supported. */
export type DeprecatedDirectiveResolver<Result> = DirectiveResolverFn<
  Result,
  DeprecatedDirectiveArgs,
  ContextType
>
export interface DeprecatedDirectiveArgs {
  /** Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted using the Markdown syntax (as specified by [CommonMark](https://commonmark.org/). */
  reason?: string
}

export interface DateTimeScalarConfig
  extends GraphQLScalarTypeConfig<DateTime, any> {
  name: 'DateTime'
}

export type IResolvers<TContext = ContextType> = {
  Query?: QueryResolvers.Resolvers<TContext>
  Organizer?: OrganizerResolvers.Resolvers<TContext>
  TwitterAccount?: TwitterAccountResolvers.Resolvers<TContext>
  Event?: EventResolvers.Resolvers<TContext>
  EventVenue?: EventVenueResolvers.Resolvers<TContext>
  Talk?: TalkResolvers.Resolvers<TContext>
  Speaker?: SpeakerResolvers.Resolvers<TContext>
  DateTime?: GraphQLScalarType
} & { [typeName: string]: never }

export type IDirectiveResolvers<Result> = {
  skip?: SkipDirectiveResolver<Result>
  include?: IncludeDirectiveResolver<Result>
  deprecated?: DeprecatedDirectiveResolver<Result>
} & { [directiveName: string]: never }
